apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wgndi9bwr-nodejs 
  janus-idp.io/tekton: wgndi9bwr-nodejs
  backstage.io/kubernetes-id: wgndi9bwr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgndi9bwr-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  