apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wgndi9bwr-nodejs
  janus-idp.io/tekton: wgndi9bwr-nodejs
  backstage.io/kubernetes-id: wgndi9bwr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgndi9bwr-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
