apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wgndi9bwr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wgndi9bwr-nodejs 
  name: wgndi9bwr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wgndi9bwr-nodejs 
